version: '3.3'

services:
  db:
    build: ./initdb
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=db_test

  api:
    image: postgrest/postgrest
    container_name: api
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/db_test
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: ${POSTGRES_USER}
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - db

  nginx:
    image: nginx:1.13
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - db

  frontend:
    build:
      context: './frontend'
    container_name: fronend
